"use client";
import Link from "next/link";
import { ArrowRight, Github, Lock, Mail, Rocket, User } from "lucide-react";
import { Button, GlassCard } from "@/components/ui";
import { createSupabaseClient } from "@/lib/supabase";

export default function LoginPage() {
  async function oauth(provider: "google" | "github") { await createSupabaseClient().auth.signInWithOAuth({ provider, options: { redirectTo: `${location.origin}/dashboard` } }); }
  return <main className="grid min-h-screen place-items-center px-5 py-10"><div className="w-full max-w-6xl lg:grid lg:grid-cols-[1fr_520px] lg:gap-16"><section className="hidden place-items-center lg:grid"><GlassCard className="max-w-xl p-12 text-center"><Rocket className="mx-auto mb-7 text-[#c1c1ff]" size={72} /><h1 className="text-5xl font-bold">Accelerate Agency Growth</h1><p className="mt-5 text-xl leading-8 text-textSecondary">AI tells you what matters and keeps revenue from slipping through cracks.</p></GlassCard></section><GlassCard className="mx-auto w-full max-w-xl p-8 md:p-10"><div className="mb-8 text-center"><div className="mx-auto mb-5 grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-indigo to-cyan font-black">Q</div><h1 className="text-4xl font-bold">Welcome back</h1><p className="mt-2 text-textSecondary">Enter your details to access your workspace</p></div><form className="space-y-5"><Field icon={<Mail />} label="Email" placeholder="name@agency.com" /><Field icon={<Lock />} label="Password" placeholder="••••••••" type="password" /><Link href="/dashboard" className="gradient-button flex items-center justify-center gap-2 px-5 py-4 font-semibold">Sign In <ArrowRight /></Link></form><div className="my-7 h-px bg-white/10" /><div className="grid gap-3 sm:grid-cols-2"><Button type="button" variant="ghost" onClick={() => oauth("google")}><User className="mr-2 inline" size={18} />Google</Button><Button type="button" variant="ghost" onClick={() => oauth("github")}><Github className="mr-2 inline" size={18} />GitHub</Button></div><p className="mt-6 text-center text-textMuted">No account? <Link href="/onboarding/workspace" className="text-[#c1c1ff]">Sign Up</Link></p></GlassCard></div></main>;
}
function Field({ label, icon, placeholder, type = "text" }: { label: string; icon: React.ReactNode; placeholder: string; type?: string }) { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.18em] text-textSecondary">{label}</span><span className="flex items-center gap-3 rounded-2xl bg-white px-4 py-4 text-slate-500">{icon}<input className="w-full bg-transparent outline-none" placeholder={placeholder} type={type} /></span></label>; }
