"use client";
import { useState } from "react";
import { Calendar, Phone, Send, Sparkles } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, GlassCard } from "@/components/ui";
import { useConversations, useLeads } from "@/lib/api";

export default function InboxPage() {
  const { data: conversations = [] } = useConversations(); const { data: leads = [] } = useLeads(); const [id, setId] = useState("conv_sarah");
  const selected = conversations.find((c) => c.id === id) ?? conversations[0]; const lead = leads.find((l) => l.id === selected?.leadId);
  return <AppShell><section className="grid min-h-[calc(100vh-120px)] overflow-hidden rounded-3xl border border-white/10 bg-white/[.03] lg:grid-cols-[320px_minmax(0,1fr)_360px]"><aside className="border-white/10 p-5 lg:border-r"><h1 className="text-3xl font-bold">Inbox</h1><div className="mt-6 space-y-3">{conversations.map((c) => <button key={c.id} onClick={() => setId(c.id)} className={`w-full rounded-2xl p-4 text-left ${c.id === selected?.id ? "bg-white/[.12] text-[#c1c1ff]" : "hover:bg-white/[.06]"}`}><div className="flex justify-between"><strong>{c.title}</strong><span className="text-sm text-textMuted">{c.updatedAt}</span></div><p className="truncate text-sm text-textSecondary">{c.lastMessage}</p></button>)}</div></aside><main className="p-5 lg:border-r lg:border-white/10"><h2 className="border-b border-white/10 pb-5 text-2xl font-bold">{selected?.title}<span className="ml-3 text-base text-textMuted">{lead?.company}</span></h2><div className="mt-7 space-y-5">{selected?.messages.map((m) => <div key={m.id} className={`max-w-[86%] rounded-3xl p-5 ${m.direction === "outbound" ? "ml-auto bg-indigo/25" : m.direction === "internal" ? "border border-dashed border-white/15 bg-white/[.04]" : "glass-card"}`}><div className="mb-2 flex justify-between text-sm"><strong>{m.sender}</strong><span className="text-textMuted">{m.sentAt}</span></div><p className="leading-7 text-textSecondary">{m.body}</p></div>)}</div><div className="glass-card sticky bottom-4 mt-8 rounded-3xl p-4"><div className="mb-3 flex gap-3"><Badge>Reply via WhatsApp</Badge><Badge tone="indigo">Internal Note</Badge></div><div className="flex gap-3"><input className="flex-1 rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3 outline-none" placeholder="Type a message..." /><Button><Send size={18} /></Button></div></div></main><aside className="p-5"><div className="mb-6 flex justify-between"><h2 className="text-xl font-bold">Lead Intelligence</h2><Sparkles className="text-cyan" /></div><GlassCard className="p-6 text-center"><div className="mx-auto mb-5 grid size-24 place-items-center rounded-3xl bg-white/[.12] text-4xl font-black">SJ</div><h3 className="text-2xl font-bold">{selected?.title}</h3><p className="text-textMuted">{lead?.company}</p><div className="mt-5 grid grid-cols-2 gap-3"><Button variant="ghost"><Phone className="mr-2 inline" size={16} />Call</Button><Button variant="ghost"><Calendar className="mr-2 inline" size={16} />Meet</Button></div></GlassCard><GlassCard className="mt-5 border-cyan/30 p-5"><p className="font-bold uppercase tracking-[.16em] text-cyan">Lead Score</p><strong className="mt-4 block text-4xl">{lead?.score ?? 92}/100</strong><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan" style={{ width: `${lead?.score ?? 92}%` }} /></div></GlassCard></aside></section></AppShell>;
}
