"use client";
import { useState } from "react";
import { Bot, Mail, Maximize2, MessageCircle, Pin, Send, Sparkles } from "lucide-react";
import { motion } from "framer-motion";
import { AppShell } from "@/components/app-shell";
import { Badge, Button, GlassCard, SectionHeader } from "@/components/ui";

const modes = ["Sales", "Support", "Founder"] as const;
export default function WorkspacePage() {
  const [mode, setMode] = useState<(typeof modes)[number]>("Support");
  return <AppShell aiPanel={<Ai mode={mode} />}><SectionHeader title={`${mode} Workspace`} description="Open every channel together, pin important windows, and let AI keep next actions visible." /><div className="mb-6 flex justify-center"><div className="glass-panel flex rounded-2xl p-1">{modes.map((m) => <button key={m} onClick={() => setMode(m)} className={`rounded-xl px-7 py-3 font-semibold ${mode === m ? "bg-white/[.12] text-[#c1c1ff]" : "text-textMuted"}`}>{m}</button>)}</div></div><section className="grid gap-6 xl:grid-cols-2"><Window title="Gmail" icon={<Mail className="text-danger" />} badge="3 New"><GlassCard className="border-cyan/30 p-5"><div className="mb-3 flex gap-2 text-cyan"><Sparkles /><strong>AI Summary</strong></div><p className="text-textSecondary">Enterprise client TechCorp is requesting a pricing tier upgrade. High priority.</p></GlassCard><Msg name="Sarah Jenkins" text="Can we jump on a call this afternoon?" /></Window><Window title="Instagram" icon={<MessageCircle className="text-[#c1c1ff]" />}><Msg name="Neon Studios" text="Loved the new campaign drop! When is the next collection launching?" /><GlassCard className="border-cyan/30 p-5"><strong className="text-cyan">Suggested Reply</strong><p className="mt-3 text-textSecondary">Thanks! The next collection drops on the 15th. Want early access?</p><div className="mt-4 flex gap-3"><Button className="flex-1">Send</Button><Button variant="ghost">Edit</Button></div></GlassCard></Window><Window title="WhatsApp Biz" icon={<MessageCircle className="text-success" />}><Badge tone="green">Hot Lead</Badge><p className="mt-3 font-bold">John Doe</p><p className="text-textMuted">+1 555-0198</p></Window><Window title="Messenger" icon={<MessageCircle className="text-info" />} badge="Pending"><div className="rounded-2xl border border-warning/30 bg-warning/10 p-5"><p className="font-bold">Mike Ross</p><p className="mt-2 text-textSecondary">I have not received my tracking number yet. Order #4492.</p></div></Window></section></AppShell>;
}
function Window({ title, icon, badge, children }: { title: string; icon: React.ReactNode; badge?: string; children: React.ReactNode }) { return <motion.article drag dragMomentum={false} className="glass-card min-h-[390px] rounded-3xl"><header className="flex items-center justify-between border-b border-white/10 p-5"><div className="flex items-center gap-3">{icon}<h2 className="text-xl font-bold">{title}</h2>{badge ? <Badge tone="red">{badge}</Badge> : null}</div><div className="flex gap-2 text-textMuted"><Pin size={18} /><Maximize2 size={18} /></div></header><div className="space-y-5 p-5">{children}</div></motion.article>; }
function Msg({ name, text }: { name: string; text: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><strong>{name}</strong><p className="mt-2 text-textSecondary">{text}</p></div>; }
function Ai({ mode }: { mode: string }) { return <div className="space-y-5"><div className="border-b border-cyan pb-4 text-cyan">AI Daily Brief</div><GlassCard className="p-5"><p className="mb-2 flex gap-2 font-bold"><Bot className="text-cyan" />High Priority</p><p className="text-textSecondary">TechCorp needs a pricing upgrade. {mode} actions are prioritized.</p><Button className="mt-5 w-full">Draft Calendar Invite</Button></GlassCard><div className="absolute bottom-6 left-6 right-6 flex gap-3 rounded-2xl border border-white/10 bg-background/80 p-3"><input className="flex-1 bg-transparent outline-none" placeholder="Ask AI..." /><Send className="text-cyan" size={18} /></div></div>; }
